/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AffiliateProfile {
  'id' : Principal,
  'referralCode' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'approved' : boolean,
  'paypalEmail' : string,
}
export interface AffiliateStats {
  'readyAmount' : bigint,
  'paidAmount' : bigint,
  'pendingAmount' : bigint,
  'totalClicks' : bigint,
  'totalConversions' : bigint,
  'commissions' : Array<CommissionEntry>,
}
export interface BirthdayDripConfigView {
  'id' : string,
  'createdAt' : bigint,
  'templateBody' : string,
  'isActive' : boolean,
}
export type CallOutcome = { 'reached' : null } |
  { 'noAnswer' : null } |
  { 'leftVoicemail' : null };
export interface CallRecord {
  'timestamp' : bigint,
  'disposition' : [] | [string],
  'outcome' : CallOutcome,
}
export interface ColdCallScriptConfig {
  'preQualifyingNeeds' : string,
  'goalType' : string,
  'packagesOrServices' : string,
  'whatYouAreSelling' : string,
}
export interface ColdCallScriptConfigInput {
  'preQualifyingNeeds' : string,
  'goalType' : string,
  'packagesOrServices' : string,
  'whatYouAreSelling' : string,
}
export interface CommissionEntry {
  'id' : string,
  'status' : CommissionStatus,
  'affiliateId' : Principal,
  'commissionAmount' : bigint,
  'planAmount' : bigint,
  'payoutEligibleDate' : bigint,
  'newUserPrincipal' : Principal,
  'paidAt' : [] | [bigint],
  'paypalEmail' : string,
  'saleDate' : bigint,
}
export type CommissionStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'ready' : null };
export interface CsvLeadInput {
  'contactName' : string,
  'city' : [] | [string],
  'name' : string,
  'email' : string,
  'state' : [] | [string],
  'birthday' : [] | [string],
  'address' : string,
  'notes' : string,
  'phone' : string,
  'industry' : [] | [string],
}
export interface DashboardStats {
  'closedWon' : bigint,
  'prospects' : bigint,
  'recentLeads' : Array<Lead>,
  'contacted' : bigint,
  'qualified' : bigint,
  'closedLost' : bigint,
}
export type DripCampaignStatus = string;
export interface DripCampaignView {
  'id' : bigint,
  'status' : DripCampaignStatus,
  'completedAt' : [] | [bigint],
  'leadIds' : Array<bigint>,
  'pausedAt' : [] | [bigint],
  'startedAt' : [] | [bigint],
  'failedLeadIds' : Array<bigint>,
  'sentLeadIds' : Array<bigint>,
  'templateId' : string,
  'name' : string,
  'createdAt' : bigint,
  'templateBody' : string,
}
export interface EmailRecord { 'id' : string, 'timestamp' : Timestamp }
export interface EmailTemplate {
  'id' : string,
  'subject' : string,
  'body' : string,
  'name' : string,
  'createdAt' : Timestamp,
}
export interface EnrichedCommissionEntry {
  'referredEmail' : string,
  'status' : string,
  'referredName' : string,
  'hasPurchased' : boolean,
  'referredPhone' : string,
  'referredBizName' : string,
  'affiliateId' : string,
  'commissionAmount' : bigint,
  'newUserPrincipal' : string,
}
export interface Lead {
  'id' : bigint,
  'pipelineId' : [] | [bigint],
  'callHistory' : Array<CallRecord>,
  'textHistory' : Array<TextRecord>,
  'city' : string,
  'qualificationTags' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'revenueRange' : string,
  'email' : string,
  'aiResearch' : [] | [string],
  'emailHistory' : Array<EmailRecord>,
  'state' : string,
  'pipelineStage' : PipelineStage,
  'birthday' : [] | [string],
  'address' : string,
  'notes' : string,
  'isImported' : boolean,
  'isDnc' : boolean,
  'phone' : string,
  'yearsInBusiness' : bigint,
  'lastName' : [] | [string],
  'isNewLeadQueued' : boolean,
  'followUpDate' : [] | [string],
  'industry' : string,
  'firstName' : [] | [string],
}
export interface LeadInput {
  'pipelineId' : [] | [bigint],
  'city' : string,
  'qualificationTags' : Array<string>,
  'name' : string,
  'revenueRange' : string,
  'email' : string,
  'state' : string,
  'pipelineStage' : PipelineStage,
  'birthday' : [] | [string],
  'address' : string,
  'notes' : string,
  'isDnc' : [] | [boolean],
  'phone' : string,
  'yearsInBusiness' : bigint,
  'lastName' : [] | [string],
  'followUpDate' : [] | [string],
  'industry' : string,
  'firstName' : [] | [string],
}
export interface LeadUpdate {
  'pipelineId' : [] | [bigint],
  'city' : [] | [string],
  'qualificationTags' : [] | [Array<string>],
  'name' : [] | [string],
  'revenueRange' : [] | [string],
  'email' : [] | [string],
  'state' : [] | [string],
  'pipelineStage' : [] | [PipelineStage],
  'birthday' : [] | [string],
  'address' : [] | [string],
  'notes' : [] | [string],
  'isDnc' : [] | [boolean],
  'phone' : [] | [string],
  'yearsInBusiness' : [] | [bigint],
  'lastName' : [] | [string],
  'followUpDate' : [] | [string],
  'industry' : [] | [string],
  'firstName' : [] | [string],
}
export type PayoutFilter = { 'all' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'ready' : null };
export interface Pipeline {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
}
export type PipelineStage = { 'Prospect' : null } |
  { 'Contacted' : null } |
  { 'Qualified' : null } |
  { 'ClosedWon' : null } |
  { 'ClosedLost' : null };
export interface PreRegisteredUser {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'phone' : string,
}
export interface ProfileInput {
  'name' : string,
  'email' : string,
  'website' : [] | [string],
  'referredBy' : [] | [string],
  'hearAboutUs' : [] | [string],
  'companyName' : string,
  'phone' : string,
}
export interface SampleBusiness {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'revenueRange' : string,
  'email' : string,
  'state' : string,
  'address' : string,
  'phone' : string,
  'yearsInBusiness' : bigint,
  'industry' : string,
}
export interface SmsTemplate {
  'id' : string,
  'body' : string,
  'name' : string,
  'createdAt' : Timestamp,
}
export interface TextRecord {
  'messageBody' : string,
  'timestamp' : bigint,
  'disposition' : [] | [string],
}
export type Timestamp = bigint;
export interface UserAdminView {
  'principal' : Principal,
  'subscribedAt' : [] | [bigint],
  'featureAccess' : boolean,
  'subscriptionTier' : string,
  'isAdmin' : boolean,
  'agreementAcceptedAt' : [] | [bigint],
  'profile' : [] | [UserProfile],
  'ipAddress' : [] | [string],
}
export interface UserExportRecord {
  'totalCommissions' : bigint,
  'principal' : string,
  'referralCode' : string,
  'subscribedAt' : [] | [bigint],
  'affiliateApproved' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'subscriptionTier' : string,
  'isPaid' : boolean,
  'email' : string,
  'website' : string,
  'referredBy' : string,
  'pendingPayouts' : bigint,
  'hearAboutUs' : string,
  'isAffiliate' : boolean,
  'totalPayouts' : bigint,
  'companyName' : string,
  'phone' : string,
  'agreementAcceptedAt' : [] | [bigint],
  'ipAddress' : string,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'website' : [] | [string],
  'referredBy' : [] | [string],
  'hearAboutUs' : [] | [string],
  'companyName' : string,
  'phone' : string,
}
export interface _SERVICE {
  'acceptLiability' : ActorMethod<
    [[] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'activatePreRegisteredUser' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addCallRecord' : ActorMethod<
    [bigint, CallOutcome],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addEmailRecord' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addEmailTemplate' : ActorMethod<[string, string, string], string>,
  'addLead' : ActorMethod<[LeadInput], bigint>,
  'addSmsTemplate' : ActorMethod<[string, string], string>,
  'addTextRecord' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminCreatePreRegisteredUser' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteAllLeads' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'adminDeletePreRegisteredUser' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteUserLeads' : ActorMethod<
    [Principal],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'adminEnsureAffiliateRecord' : ActorMethod<
    [Principal, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetEnrichedPayouts' : ActorMethod<[], Array<EnrichedCommissionEntry>>,
  'adminGetPreRegisteredUsers' : ActorMethod<[], Array<PreRegisteredUser>>,
  'bulkDeleteLeads' : ActorMethod<
    [Array<bigint>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'bulkImportLeads' : ActorMethod<
    [Array<CsvLeadInput>, PipelineStage, [] | [bigint]],
    Array<bigint>
  >,
  'checkFeatureAccess' : ActorMethod<[], boolean>,
  'checkPreRegisteredByEmail' : ActorMethod<[string], boolean>,
  'checkSubscription' : ActorMethod<[], boolean>,
  'checkSubscriptionStatus' : ActorMethod<
    [],
    { 'tier' : string, 'isSubscribed' : boolean }
  >,
  'clearNewLeadQueued' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createDripCampaign' : ActorMethod<
    [string, string, string, Array<bigint>],
    { 'ok' : DripCampaignView } |
      { 'err' : string }
  >,
  'createPipeline' : ActorMethod<
    [string],
    { 'ok' : Pipeline } |
      { 'err' : string }
  >,
  'deleteDripCampaign' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteEmailTemplate' : ActorMethod<[string], boolean>,
  'deleteLead' : ActorMethod<[bigint], boolean>,
  'deletePipeline' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteSmsTemplate' : ActorMethod<[string], boolean>,
  'generateUserExport' : ActorMethod<
    [],
    { 'ok' : Array<UserExportRecord> } |
      { 'err' : string }
  >,
  'getAdminUserList' : ActorMethod<[], Array<UserAdminView>>,
  'getAffiliate' : ActorMethod<[], [] | [AffiliateProfile]>,
  'getAffiliateStats' : ActorMethod<[], AffiliateStats>,
  'getAllAffiliates' : ActorMethod<[], Array<AffiliateProfile>>,
  'getAllUsers' : ActorMethod<
    [],
    { 'ok' : Array<UserAdminView> } |
      { 'err' : string }
  >,
  'getBirthdayDripConfig' : ActorMethod<
    [],
    { 'ok' : BirthdayDripConfigView } |
      { 'err' : string }
  >,
  'getBirthdayLeads' : ActorMethod<[], Array<Lead>>,
  'getCallDispositions' : ActorMethod<[], Array<string>>,
  'getColdCallConfig' : ActorMethod<
    [],
    { 'ok' : ColdCallScriptConfig } |
      { 'err' : string }
  >,
  'getDashboardStats' : ActorMethod<[[] | [bigint]], DashboardStats>,
  'getDripCampaign' : ActorMethod<
    [bigint],
    { 'ok' : DripCampaignView } |
      { 'err' : string }
  >,
  'getDripCampaigns' : ActorMethod<[], Array<DripCampaignView>>,
  'getEmailTemplates' : ActorMethod<[], Array<EmailTemplate>>,
  'getEnrichedAffiliateStats' : ActorMethod<[], Array<EnrichedCommissionEntry>>,
  'getLead' : ActorMethod<[bigint], [] | [Lead]>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getLiabilityStatus' : ActorMethod<[], boolean>,
  'getNewLeadQueue' : ActorMethod<[], Array<Lead>>,
  'getPackageConfig' : ActorMethod<
    [],
    Array<{ 'tier' : string, 'enabled' : boolean }>
  >,
  'getPayouts' : ActorMethod<[PayoutFilter], Array<CommissionEntry>>,
  'getPipelines' : ActorMethod<[], Array<Pipeline>>,
  'getSampleBusinesses' : ActorMethod<[], Array<SampleBusiness>>,
  'getShowComingSoonTeaser' : ActorMethod<[], boolean>,
  'getSmsTemplates' : ActorMethod<[], Array<SmsTemplate>>,
  'getSubscriptionTier' : ActorMethod<[], string>,
  'getUserCount' : ActorMethod<[], { 'ok' : bigint } | { 'err' : string }>,
  'getUserProfile' : ActorMethod<
    [],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'grantAdmin' : ActorMethod<[Principal], { 'ok' : null } | { 'err' : string }>,
  'importSampleBusiness' : ActorMethod<[bigint], [] | [bigint]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'markLeadFailed' : ActorMethod<
    [bigint, bigint],
    { 'ok' : DripCampaignView } |
      { 'err' : string }
  >,
  'markLeadSent' : ActorMethod<
    [bigint, bigint],
    { 'ok' : DripCampaignView } |
      { 'err' : string }
  >,
  'markPayoutPaid' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markSubscribed' : ActorMethod<[], undefined>,
  'pauseDripCampaign' : ActorMethod<
    [bigint],
    { 'ok' : DripCampaignView } |
      { 'err' : string }
  >,
  'recordConversion' : ActorMethod<[string], undefined>,
  'registerAffiliate' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'restoreUserAccess' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resumeDripCampaign' : ActorMethod<
    [bigint],
    { 'ok' : DripCampaignView } |
      { 'err' : string }
  >,
  'revokeUserAccess' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveColdCallConfig' : ActorMethod<
    [ColdCallScriptConfigInput],
    { 'ok' : ColdCallScriptConfig } |
      { 'err' : string }
  >,
  'saveUserProfile' : ActorMethod<
    [ProfileInput],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'sendSupportContactEmail' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setBirthdayDripConfig' : ActorMethod<
    [string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setPackageEnabled' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setShowComingSoonTeaser' : ActorMethod<
    [boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setSubscriptionTier' : ActorMethod<[string], undefined>,
  'setUserTier' : ActorMethod<
    [Principal, string],
    { 'ok' : { 'tier' : string } } |
      { 'err' : string }
  >,
  'spinSms' : ActorMethod<
    [string, bigint],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'stopDripCampaign' : ActorMethod<
    [bigint],
    { 'ok' : DripCampaignView } |
      { 'err' : string }
  >,
  'trackReferralClick' : ActorMethod<[string], undefined>,
  'updateAffiliatePaypalEmail' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateEmailTemplate' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [string]],
    boolean
  >,
  'updateLead' : ActorMethod<[bigint, LeadUpdate], boolean>,
  'updateLeadDnc' : ActorMethod<
    [bigint, boolean],
    { 'ok' : Lead } |
      { 'err' : string }
  >,
  'updatePipeline' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSmsTemplate' : ActorMethod<
    [string, [] | [string], [] | [string]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];