/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CallOutcome = IDL.Variant({
  'reached' : IDL.Null,
  'noAnswer' : IDL.Null,
  'leftVoicemail' : IDL.Null,
});
export const PipelineStage = IDL.Variant({
  'Prospect' : IDL.Null,
  'Contacted' : IDL.Null,
  'Qualified' : IDL.Null,
  'ClosedWon' : IDL.Null,
  'ClosedLost' : IDL.Null,
});
export const LeadInput = IDL.Record({
  'pipelineId' : IDL.Opt(IDL.Nat),
  'city' : IDL.Text,
  'qualificationTags' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'revenueRange' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'pipelineStage' : PipelineStage,
  'birthday' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'isDnc' : IDL.Opt(IDL.Bool),
  'phone' : IDL.Text,
  'yearsInBusiness' : IDL.Nat,
  'lastName' : IDL.Opt(IDL.Text),
  'followUpDate' : IDL.Opt(IDL.Text),
  'industry' : IDL.Text,
  'firstName' : IDL.Opt(IDL.Text),
});
export const EnrichedCommissionEntry = IDL.Record({
  'referredEmail' : IDL.Text,
  'status' : IDL.Text,
  'referredName' : IDL.Text,
  'hasPurchased' : IDL.Bool,
  'referredPhone' : IDL.Text,
  'referredBizName' : IDL.Text,
  'affiliateId' : IDL.Text,
  'commissionAmount' : IDL.Nat,
  'newUserPrincipal' : IDL.Text,
});
export const PreRegisteredUser = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CsvLeadInput = IDL.Record({
  'contactName' : IDL.Text,
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'birthday' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'industry' : IDL.Opt(IDL.Text),
});
export const DripCampaignStatus = IDL.Text;
export const DripCampaignView = IDL.Record({
  'id' : IDL.Nat,
  'status' : DripCampaignStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'leadIds' : IDL.Vec(IDL.Nat),
  'pausedAt' : IDL.Opt(IDL.Int),
  'startedAt' : IDL.Opt(IDL.Int),
  'failedLeadIds' : IDL.Vec(IDL.Nat),
  'sentLeadIds' : IDL.Vec(IDL.Nat),
  'templateId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'templateBody' : IDL.Text,
});
export const Pipeline = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserExportRecord = IDL.Record({
  'totalCommissions' : IDL.Nat,
  'principal' : IDL.Text,
  'referralCode' : IDL.Text,
  'subscribedAt' : IDL.Opt(IDL.Int),
  'affiliateApproved' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'subscriptionTier' : IDL.Text,
  'isPaid' : IDL.Bool,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'referredBy' : IDL.Text,
  'pendingPayouts' : IDL.Nat,
  'hearAboutUs' : IDL.Text,
  'isAffiliate' : IDL.Bool,
  'totalPayouts' : IDL.Nat,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'agreementAcceptedAt' : IDL.Opt(IDL.Int),
  'ipAddress' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'referredBy' : IDL.Opt(IDL.Text),
  'hearAboutUs' : IDL.Opt(IDL.Text),
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserAdminView = IDL.Record({
  'principal' : IDL.Principal,
  'subscribedAt' : IDL.Opt(IDL.Int),
  'featureAccess' : IDL.Bool,
  'subscriptionTier' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'agreementAcceptedAt' : IDL.Opt(IDL.Int),
  'profile' : IDL.Opt(UserProfile),
  'ipAddress' : IDL.Opt(IDL.Text),
});
export const AffiliateProfile = IDL.Record({
  'id' : IDL.Principal,
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'approved' : IDL.Bool,
  'paypalEmail' : IDL.Text,
});
export const CommissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'ready' : IDL.Null,
});
export const CommissionEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : CommissionStatus,
  'affiliateId' : IDL.Principal,
  'commissionAmount' : IDL.Nat,
  'planAmount' : IDL.Nat,
  'payoutEligibleDate' : IDL.Int,
  'newUserPrincipal' : IDL.Principal,
  'paidAt' : IDL.Opt(IDL.Int),
  'paypalEmail' : IDL.Text,
  'saleDate' : IDL.Int,
});
export const AffiliateStats = IDL.Record({
  'readyAmount' : IDL.Nat,
  'paidAmount' : IDL.Nat,
  'pendingAmount' : IDL.Nat,
  'totalClicks' : IDL.Nat,
  'totalConversions' : IDL.Nat,
  'commissions' : IDL.Vec(CommissionEntry),
});
export const BirthdayDripConfigView = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'templateBody' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const CallRecord = IDL.Record({
  'timestamp' : IDL.Int,
  'disposition' : IDL.Opt(IDL.Text),
  'outcome' : CallOutcome,
});
export const TextRecord = IDL.Record({
  'messageBody' : IDL.Text,
  'timestamp' : IDL.Int,
  'disposition' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Int;
export const EmailRecord = IDL.Record({
  'id' : IDL.Text,
  'timestamp' : Timestamp,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'pipelineId' : IDL.Opt(IDL.Nat),
  'callHistory' : IDL.Vec(CallRecord),
  'textHistory' : IDL.Vec(TextRecord),
  'city' : IDL.Text,
  'qualificationTags' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'revenueRange' : IDL.Text,
  'email' : IDL.Text,
  'aiResearch' : IDL.Opt(IDL.Text),
  'emailHistory' : IDL.Vec(EmailRecord),
  'state' : IDL.Text,
  'pipelineStage' : PipelineStage,
  'birthday' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'isImported' : IDL.Bool,
  'isDnc' : IDL.Bool,
  'phone' : IDL.Text,
  'yearsInBusiness' : IDL.Nat,
  'lastName' : IDL.Opt(IDL.Text),
  'isNewLeadQueued' : IDL.Bool,
  'followUpDate' : IDL.Opt(IDL.Text),
  'industry' : IDL.Text,
  'firstName' : IDL.Opt(IDL.Text),
});
export const ColdCallScriptConfig = IDL.Record({
  'preQualifyingNeeds' : IDL.Text,
  'goalType' : IDL.Text,
  'packagesOrServices' : IDL.Text,
  'whatYouAreSelling' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'closedWon' : IDL.Nat,
  'prospects' : IDL.Nat,
  'recentLeads' : IDL.Vec(Lead),
  'contacted' : IDL.Nat,
  'qualified' : IDL.Nat,
  'closedLost' : IDL.Nat,
});
export const EmailTemplate = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const PayoutFilter = IDL.Variant({
  'all' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'ready' : IDL.Null,
});
export const SampleBusiness = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'revenueRange' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'yearsInBusiness' : IDL.Nat,
  'industry' : IDL.Text,
});
export const SmsTemplate = IDL.Record({
  'id' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const ColdCallScriptConfigInput = IDL.Record({
  'preQualifyingNeeds' : IDL.Text,
  'goalType' : IDL.Text,
  'packagesOrServices' : IDL.Text,
  'whatYouAreSelling' : IDL.Text,
});
export const ProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'referredBy' : IDL.Opt(IDL.Text),
  'hearAboutUs' : IDL.Opt(IDL.Text),
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadUpdate = IDL.Record({
  'pipelineId' : IDL.Opt(IDL.Nat),
  'city' : IDL.Opt(IDL.Text),
  'qualificationTags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'name' : IDL.Opt(IDL.Text),
  'revenueRange' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'pipelineStage' : IDL.Opt(PipelineStage),
  'birthday' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'isDnc' : IDL.Opt(IDL.Bool),
  'phone' : IDL.Opt(IDL.Text),
  'yearsInBusiness' : IDL.Opt(IDL.Nat),
  'lastName' : IDL.Opt(IDL.Text),
  'followUpDate' : IDL.Opt(IDL.Text),
  'industry' : IDL.Opt(IDL.Text),
  'firstName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'acceptLiability' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'activatePreRegisteredUser' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addCallRecord' : IDL.Func(
      [IDL.Nat, CallOutcome],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addEmailRecord' : IDL.Func(
      [IDL.Nat, IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addEmailTemplate' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'addLead' : IDL.Func([LeadInput], [IDL.Nat], []),
  'addSmsTemplate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addTextRecord' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminCreatePreRegisteredUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteAllLeads' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'adminDeletePreRegisteredUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteUserLeads' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'adminEnsureAffiliateRecord' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetEnrichedPayouts' : IDL.Func(
      [],
      [IDL.Vec(EnrichedCommissionEntry)],
      [],
    ),
  'adminGetPreRegisteredUsers' : IDL.Func([], [IDL.Vec(PreRegisteredUser)], []),
  'bulkDeleteLeads' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'bulkImportLeads' : IDL.Func(
      [IDL.Vec(CsvLeadInput), PipelineStage, IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'checkFeatureAccess' : IDL.Func([], [IDL.Bool], []),
  'checkPreRegisteredByEmail' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'checkSubscription' : IDL.Func([], [IDL.Bool], []),
  'checkSubscriptionStatus' : IDL.Func(
      [],
      [IDL.Record({ 'tier' : IDL.Text, 'isSubscribed' : IDL.Bool })],
      [],
    ),
  'clearNewLeadQueued' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createDripCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
      [],
    ),
  'createPipeline' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Pipeline, 'err' : IDL.Text })],
      [],
    ),
  'deleteDripCampaign' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteEmailTemplate' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePipeline' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteSmsTemplate' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generateUserExport' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(UserExportRecord), 'err' : IDL.Text })],
      [],
    ),
  'getAdminUserList' : IDL.Func([], [IDL.Vec(UserAdminView)], []),
  'getAffiliate' : IDL.Func([], [IDL.Opt(AffiliateProfile)], ['query']),
  'getAffiliateStats' : IDL.Func([], [AffiliateStats], []),
  'getAllAffiliates' : IDL.Func([], [IDL.Vec(AffiliateProfile)], []),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(UserAdminView), 'err' : IDL.Text })],
      [],
    ),
  'getBirthdayDripConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : BirthdayDripConfigView, 'err' : IDL.Text })],
      ['query'],
    ),
  'getBirthdayLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getCallDispositions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getColdCallConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : ColdCallScriptConfig, 'err' : IDL.Text })],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [DashboardStats],
      ['query'],
    ),
  'getDripCampaign' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
      ['query'],
    ),
  'getDripCampaigns' : IDL.Func([], [IDL.Vec(DripCampaignView)], ['query']),
  'getEmailTemplates' : IDL.Func([], [IDL.Vec(EmailTemplate)], ['query']),
  'getEnrichedAffiliateStats' : IDL.Func(
      [],
      [IDL.Vec(EnrichedCommissionEntry)],
      [],
    ),
  'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLiabilityStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getNewLeadQueue' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getPackageConfig' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'tier' : IDL.Text, 'enabled' : IDL.Bool }))],
      ['query'],
    ),
  'getPayouts' : IDL.Func([PayoutFilter], [IDL.Vec(CommissionEntry)], []),
  'getPipelines' : IDL.Func([], [IDL.Vec(Pipeline)], ['query']),
  'getSampleBusinesses' : IDL.Func([], [IDL.Vec(SampleBusiness)], ['query']),
  'getShowComingSoonTeaser' : IDL.Func([], [IDL.Bool], ['query']),
  'getSmsTemplates' : IDL.Func([], [IDL.Vec(SmsTemplate)], ['query']),
  'getSubscriptionTier' : IDL.Func([], [IDL.Text], []),
  'getUserCount' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'grantAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'importSampleBusiness' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], []),
  'markLeadFailed' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
      [],
    ),
  'markLeadSent' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
      [],
    ),
  'markPayoutPaid' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markSubscribed' : IDL.Func([], [], []),
  'pauseDripCampaign' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
      [],
    ),
  'recordConversion' : IDL.Func([IDL.Text], [], []),
  'registerAffiliate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'restoreUserAccess' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resumeDripCampaign' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
      [],
    ),
  'revokeUserAccess' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveColdCallConfig' : IDL.Func(
      [ColdCallScriptConfigInput],
      [IDL.Variant({ 'ok' : ColdCallScriptConfig, 'err' : IDL.Text })],
      [],
    ),
  'saveUserProfile' : IDL.Func(
      [ProfileInput],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'sendSupportContactEmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setBirthdayDripConfig' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setPackageEnabled' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setShowComingSoonTeaser' : IDL.Func(
      [IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setSubscriptionTier' : IDL.Func([IDL.Text], [], []),
  'setUserTier' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'tier' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'spinSms' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'stopDripCampaign' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
      [],
    ),
  'trackReferralClick' : IDL.Func([IDL.Text], [], []),
  'updateAffiliatePaypalEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateEmailTemplate' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateLead' : IDL.Func([IDL.Nat, LeadUpdate], [IDL.Bool], []),
  'updateLeadDnc' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      [],
    ),
  'updatePipeline' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateSmsTemplate' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CallOutcome = IDL.Variant({
    'reached' : IDL.Null,
    'noAnswer' : IDL.Null,
    'leftVoicemail' : IDL.Null,
  });
  const PipelineStage = IDL.Variant({
    'Prospect' : IDL.Null,
    'Contacted' : IDL.Null,
    'Qualified' : IDL.Null,
    'ClosedWon' : IDL.Null,
    'ClosedLost' : IDL.Null,
  });
  const LeadInput = IDL.Record({
    'pipelineId' : IDL.Opt(IDL.Nat),
    'city' : IDL.Text,
    'qualificationTags' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'revenueRange' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'pipelineStage' : PipelineStage,
    'birthday' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'isDnc' : IDL.Opt(IDL.Bool),
    'phone' : IDL.Text,
    'yearsInBusiness' : IDL.Nat,
    'lastName' : IDL.Opt(IDL.Text),
    'followUpDate' : IDL.Opt(IDL.Text),
    'industry' : IDL.Text,
    'firstName' : IDL.Opt(IDL.Text),
  });
  const EnrichedCommissionEntry = IDL.Record({
    'referredEmail' : IDL.Text,
    'status' : IDL.Text,
    'referredName' : IDL.Text,
    'hasPurchased' : IDL.Bool,
    'referredPhone' : IDL.Text,
    'referredBizName' : IDL.Text,
    'affiliateId' : IDL.Text,
    'commissionAmount' : IDL.Nat,
    'newUserPrincipal' : IDL.Text,
  });
  const PreRegisteredUser = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CsvLeadInput = IDL.Record({
    'contactName' : IDL.Text,
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'birthday' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'industry' : IDL.Opt(IDL.Text),
  });
  const DripCampaignStatus = IDL.Text;
  const DripCampaignView = IDL.Record({
    'id' : IDL.Nat,
    'status' : DripCampaignStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'leadIds' : IDL.Vec(IDL.Nat),
    'pausedAt' : IDL.Opt(IDL.Int),
    'startedAt' : IDL.Opt(IDL.Int),
    'failedLeadIds' : IDL.Vec(IDL.Nat),
    'sentLeadIds' : IDL.Vec(IDL.Nat),
    'templateId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'templateBody' : IDL.Text,
  });
  const Pipeline = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserExportRecord = IDL.Record({
    'totalCommissions' : IDL.Nat,
    'principal' : IDL.Text,
    'referralCode' : IDL.Text,
    'subscribedAt' : IDL.Opt(IDL.Int),
    'affiliateApproved' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'subscriptionTier' : IDL.Text,
    'isPaid' : IDL.Bool,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'referredBy' : IDL.Text,
    'pendingPayouts' : IDL.Nat,
    'hearAboutUs' : IDL.Text,
    'isAffiliate' : IDL.Bool,
    'totalPayouts' : IDL.Nat,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'agreementAcceptedAt' : IDL.Opt(IDL.Int),
    'ipAddress' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'referredBy' : IDL.Opt(IDL.Text),
    'hearAboutUs' : IDL.Opt(IDL.Text),
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserAdminView = IDL.Record({
    'principal' : IDL.Principal,
    'subscribedAt' : IDL.Opt(IDL.Int),
    'featureAccess' : IDL.Bool,
    'subscriptionTier' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'agreementAcceptedAt' : IDL.Opt(IDL.Int),
    'profile' : IDL.Opt(UserProfile),
    'ipAddress' : IDL.Opt(IDL.Text),
  });
  const AffiliateProfile = IDL.Record({
    'id' : IDL.Principal,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'approved' : IDL.Bool,
    'paypalEmail' : IDL.Text,
  });
  const CommissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'ready' : IDL.Null,
  });
  const CommissionEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : CommissionStatus,
    'affiliateId' : IDL.Principal,
    'commissionAmount' : IDL.Nat,
    'planAmount' : IDL.Nat,
    'payoutEligibleDate' : IDL.Int,
    'newUserPrincipal' : IDL.Principal,
    'paidAt' : IDL.Opt(IDL.Int),
    'paypalEmail' : IDL.Text,
    'saleDate' : IDL.Int,
  });
  const AffiliateStats = IDL.Record({
    'readyAmount' : IDL.Nat,
    'paidAmount' : IDL.Nat,
    'pendingAmount' : IDL.Nat,
    'totalClicks' : IDL.Nat,
    'totalConversions' : IDL.Nat,
    'commissions' : IDL.Vec(CommissionEntry),
  });
  const BirthdayDripConfigView = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'templateBody' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const CallRecord = IDL.Record({
    'timestamp' : IDL.Int,
    'disposition' : IDL.Opt(IDL.Text),
    'outcome' : CallOutcome,
  });
  const TextRecord = IDL.Record({
    'messageBody' : IDL.Text,
    'timestamp' : IDL.Int,
    'disposition' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const EmailRecord = IDL.Record({ 'id' : IDL.Text, 'timestamp' : Timestamp });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'pipelineId' : IDL.Opt(IDL.Nat),
    'callHistory' : IDL.Vec(CallRecord),
    'textHistory' : IDL.Vec(TextRecord),
    'city' : IDL.Text,
    'qualificationTags' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'revenueRange' : IDL.Text,
    'email' : IDL.Text,
    'aiResearch' : IDL.Opt(IDL.Text),
    'emailHistory' : IDL.Vec(EmailRecord),
    'state' : IDL.Text,
    'pipelineStage' : PipelineStage,
    'birthday' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'isImported' : IDL.Bool,
    'isDnc' : IDL.Bool,
    'phone' : IDL.Text,
    'yearsInBusiness' : IDL.Nat,
    'lastName' : IDL.Opt(IDL.Text),
    'isNewLeadQueued' : IDL.Bool,
    'followUpDate' : IDL.Opt(IDL.Text),
    'industry' : IDL.Text,
    'firstName' : IDL.Opt(IDL.Text),
  });
  const ColdCallScriptConfig = IDL.Record({
    'preQualifyingNeeds' : IDL.Text,
    'goalType' : IDL.Text,
    'packagesOrServices' : IDL.Text,
    'whatYouAreSelling' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'closedWon' : IDL.Nat,
    'prospects' : IDL.Nat,
    'recentLeads' : IDL.Vec(Lead),
    'contacted' : IDL.Nat,
    'qualified' : IDL.Nat,
    'closedLost' : IDL.Nat,
  });
  const EmailTemplate = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const PayoutFilter = IDL.Variant({
    'all' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'ready' : IDL.Null,
  });
  const SampleBusiness = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'revenueRange' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'yearsInBusiness' : IDL.Nat,
    'industry' : IDL.Text,
  });
  const SmsTemplate = IDL.Record({
    'id' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const ColdCallScriptConfigInput = IDL.Record({
    'preQualifyingNeeds' : IDL.Text,
    'goalType' : IDL.Text,
    'packagesOrServices' : IDL.Text,
    'whatYouAreSelling' : IDL.Text,
  });
  const ProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'referredBy' : IDL.Opt(IDL.Text),
    'hearAboutUs' : IDL.Opt(IDL.Text),
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadUpdate = IDL.Record({
    'pipelineId' : IDL.Opt(IDL.Nat),
    'city' : IDL.Opt(IDL.Text),
    'qualificationTags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'name' : IDL.Opt(IDL.Text),
    'revenueRange' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'pipelineStage' : IDL.Opt(PipelineStage),
    'birthday' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'isDnc' : IDL.Opt(IDL.Bool),
    'phone' : IDL.Opt(IDL.Text),
    'yearsInBusiness' : IDL.Opt(IDL.Nat),
    'lastName' : IDL.Opt(IDL.Text),
    'followUpDate' : IDL.Opt(IDL.Text),
    'industry' : IDL.Opt(IDL.Text),
    'firstName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'acceptLiability' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'activatePreRegisteredUser' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addCallRecord' : IDL.Func(
        [IDL.Nat, CallOutcome],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addEmailRecord' : IDL.Func(
        [IDL.Nat, IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addEmailTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addLead' : IDL.Func([LeadInput], [IDL.Nat], []),
    'addSmsTemplate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addTextRecord' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminCreatePreRegisteredUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteAllLeads' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'adminDeletePreRegisteredUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteUserLeads' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'adminEnsureAffiliateRecord' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetEnrichedPayouts' : IDL.Func(
        [],
        [IDL.Vec(EnrichedCommissionEntry)],
        [],
      ),
    'adminGetPreRegisteredUsers' : IDL.Func(
        [],
        [IDL.Vec(PreRegisteredUser)],
        [],
      ),
    'bulkDeleteLeads' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'bulkImportLeads' : IDL.Func(
        [IDL.Vec(CsvLeadInput), PipelineStage, IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'checkFeatureAccess' : IDL.Func([], [IDL.Bool], []),
    'checkPreRegisteredByEmail' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'checkSubscription' : IDL.Func([], [IDL.Bool], []),
    'checkSubscriptionStatus' : IDL.Func(
        [],
        [IDL.Record({ 'tier' : IDL.Text, 'isSubscribed' : IDL.Bool })],
        [],
      ),
    'clearNewLeadQueued' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createDripCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
        [],
      ),
    'createPipeline' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Pipeline, 'err' : IDL.Text })],
        [],
      ),
    'deleteDripCampaign' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteEmailTemplate' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePipeline' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteSmsTemplate' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generateUserExport' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(UserExportRecord), 'err' : IDL.Text })],
        [],
      ),
    'getAdminUserList' : IDL.Func([], [IDL.Vec(UserAdminView)], []),
    'getAffiliate' : IDL.Func([], [IDL.Opt(AffiliateProfile)], ['query']),
    'getAffiliateStats' : IDL.Func([], [AffiliateStats], []),
    'getAllAffiliates' : IDL.Func([], [IDL.Vec(AffiliateProfile)], []),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(UserAdminView), 'err' : IDL.Text })],
        [],
      ),
    'getBirthdayDripConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : BirthdayDripConfigView, 'err' : IDL.Text })],
        ['query'],
      ),
    'getBirthdayLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getCallDispositions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getColdCallConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : ColdCallScriptConfig, 'err' : IDL.Text })],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [DashboardStats],
        ['query'],
      ),
    'getDripCampaign' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
        ['query'],
      ),
    'getDripCampaigns' : IDL.Func([], [IDL.Vec(DripCampaignView)], ['query']),
    'getEmailTemplates' : IDL.Func([], [IDL.Vec(EmailTemplate)], ['query']),
    'getEnrichedAffiliateStats' : IDL.Func(
        [],
        [IDL.Vec(EnrichedCommissionEntry)],
        [],
      ),
    'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLiabilityStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getNewLeadQueue' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getPackageConfig' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'tier' : IDL.Text, 'enabled' : IDL.Bool }))],
        ['query'],
      ),
    'getPayouts' : IDL.Func([PayoutFilter], [IDL.Vec(CommissionEntry)], []),
    'getPipelines' : IDL.Func([], [IDL.Vec(Pipeline)], ['query']),
    'getSampleBusinesses' : IDL.Func([], [IDL.Vec(SampleBusiness)], ['query']),
    'getShowComingSoonTeaser' : IDL.Func([], [IDL.Bool], ['query']),
    'getSmsTemplates' : IDL.Func([], [IDL.Vec(SmsTemplate)], ['query']),
    'getSubscriptionTier' : IDL.Func([], [IDL.Text], []),
    'getUserCount' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'grantAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'importSampleBusiness' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], []),
    'markLeadFailed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
        [],
      ),
    'markLeadSent' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
        [],
      ),
    'markPayoutPaid' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markSubscribed' : IDL.Func([], [], []),
    'pauseDripCampaign' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
        [],
      ),
    'recordConversion' : IDL.Func([IDL.Text], [], []),
    'registerAffiliate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'restoreUserAccess' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resumeDripCampaign' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
        [],
      ),
    'revokeUserAccess' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveColdCallConfig' : IDL.Func(
        [ColdCallScriptConfigInput],
        [IDL.Variant({ 'ok' : ColdCallScriptConfig, 'err' : IDL.Text })],
        [],
      ),
    'saveUserProfile' : IDL.Func(
        [ProfileInput],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'sendSupportContactEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setBirthdayDripConfig' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setPackageEnabled' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setShowComingSoonTeaser' : IDL.Func(
        [IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setSubscriptionTier' : IDL.Func([IDL.Text], [], []),
    'setUserTier' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'tier' : IDL.Text }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'spinSms' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'stopDripCampaign' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : DripCampaignView, 'err' : IDL.Text })],
        [],
      ),
    'trackReferralClick' : IDL.Func([IDL.Text], [], []),
    'updateAffiliatePaypalEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateEmailTemplate' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateLead' : IDL.Func([IDL.Nat, LeadUpdate], [IDL.Bool], []),
    'updateLeadDnc' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        [],
      ),
    'updatePipeline' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateSmsTemplate' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };